"""add user to persons relationship.

Revision ID: 85815a1eec80
Revises: 33fcb659c7e9
Create Date: 2023-09-23 21:00:55.957345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85815a1eec80'
down_revision: Union[str, None] = '33fcb659c7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("INSERT INTO users (id, login, password, email, created_at, refresh_token, disabled) VALUES (0, 'admin', 'admin', 'admin@localhost', NOW(), NULL, FALSE)")
    op.execute("UPDATE persons SET user_id = 0")
    op.alter_column('persons', 'user_id', nullable=False)
    op.drop_constraint('uc_groups', 'persons', type_='unique')
    op.create_unique_constraint('uc_persons', 'persons', ['user_id', 'first_name', 'last_name'])
    op.create_foreign_key(None, 'persons', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persons_user_id_fkey', 'persons', type_='foreignkey')
    op.drop_constraint('uc_persons', 'persons', type_='unique')
    op.create_unique_constraint('uc_groups', 'persons', ['first_name', 'last_name'])
    op.drop_column('persons', 'user_id')
    op.execute("DELETE FROM users WHERE id = 0")
    # ### end Alembic commands ###
