"""add user roles.

Revision ID: 4312ea33ffd6
Revises: c5a650ebbcba
Create Date: 2023-09-24 22:30:39.167999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4312ea33ffd6'
down_revision: Union[str, None] = 'c5a650ebbcba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uc_user_roles')
    )
    # admin roles
    op.execute("INSERT INTO user_roles (user_id, role_id) VALUES (1, 1)")
    op.execute("INSERT INTO user_roles (user_id, role_id) VALUES (1, 2)")
    op.execute("INSERT INTO user_roles (user_id, role_id) VALUES (1, 3)")
    # moder roles
    op.execute("INSERT INTO user_roles (user_id, role_id) VALUES (2, 2)")
    op.execute("INSERT INTO user_roles (user_id, role_id) VALUES (2, 3)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    # ### end Alembic commands ###
