"""Add users.reset_password_token

Revision ID: c18d8d8167ae
Revises: f5887e80ac9d
Create Date: 2023-09-27 14:44:15.355625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18d8d8167ae'
down_revision: Union[str, None] = 'f5887e80ac9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
